/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package magicalpipelines.model;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class TranslatedFixation extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -8158666047940078997L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"TranslatedFixation\",\"namespace\":\"magicalpipelines.model\",\"fields\":[{\"name\":\"Timestamp\",\"type\":\"long\"},{\"name\":\"Xpos\",\"type\":\"double\"},{\"name\":\"Ypos\",\"type\":\"double\"},{\"name\":\"PupilSize\",\"type\":\"double\"},{\"name\":\"FixationDuration\",\"type\":\"double\"},{\"name\":\"AOI\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<TranslatedFixation> ENCODER =
      new BinaryMessageEncoder<TranslatedFixation>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<TranslatedFixation> DECODER =
      new BinaryMessageDecoder<TranslatedFixation>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<TranslatedFixation> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<TranslatedFixation> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<TranslatedFixation>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this TranslatedFixation to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a TranslatedFixation from a ByteBuffer. */
  public static TranslatedFixation fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public long Timestamp;
  @Deprecated public double Xpos;
  @Deprecated public double Ypos;
  @Deprecated public double PupilSize;
  @Deprecated public double FixationDuration;
  @Deprecated public java.lang.CharSequence AOI;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public TranslatedFixation() {}

  /**
   * All-args constructor.
   * @param Timestamp The new value for Timestamp
   * @param Xpos The new value for Xpos
   * @param Ypos The new value for Ypos
   * @param PupilSize The new value for PupilSize
   * @param FixationDuration The new value for FixationDuration
   * @param AOI The new value for AOI
   */
  public TranslatedFixation(java.lang.Long Timestamp, java.lang.Double Xpos, java.lang.Double Ypos, java.lang.Double PupilSize, java.lang.Double FixationDuration, java.lang.CharSequence AOI) {
    this.Timestamp = Timestamp;
    this.Xpos = Xpos;
    this.Ypos = Ypos;
    this.PupilSize = PupilSize;
    this.FixationDuration = FixationDuration;
    this.AOI = AOI;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return Timestamp;
    case 1: return Xpos;
    case 2: return Ypos;
    case 3: return PupilSize;
    case 4: return FixationDuration;
    case 5: return AOI;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: Timestamp = (java.lang.Long)value$; break;
    case 1: Xpos = (java.lang.Double)value$; break;
    case 2: Ypos = (java.lang.Double)value$; break;
    case 3: PupilSize = (java.lang.Double)value$; break;
    case 4: FixationDuration = (java.lang.Double)value$; break;
    case 5: AOI = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'Timestamp' field.
   * @return The value of the 'Timestamp' field.
   */
  public java.lang.Long getTimestamp() {
    return Timestamp;
  }

  /**
   * Sets the value of the 'Timestamp' field.
   * @param value the value to set.
   */
  public void setTimestamp(java.lang.Long value) {
    this.Timestamp = value;
  }

  /**
   * Gets the value of the 'Xpos' field.
   * @return The value of the 'Xpos' field.
   */
  public java.lang.Double getXpos() {
    return Xpos;
  }

  /**
   * Sets the value of the 'Xpos' field.
   * @param value the value to set.
   */
  public void setXpos(java.lang.Double value) {
    this.Xpos = value;
  }

  /**
   * Gets the value of the 'Ypos' field.
   * @return The value of the 'Ypos' field.
   */
  public java.lang.Double getYpos() {
    return Ypos;
  }

  /**
   * Sets the value of the 'Ypos' field.
   * @param value the value to set.
   */
  public void setYpos(java.lang.Double value) {
    this.Ypos = value;
  }

  /**
   * Gets the value of the 'PupilSize' field.
   * @return The value of the 'PupilSize' field.
   */
  public java.lang.Double getPupilSize() {
    return PupilSize;
  }

  /**
   * Sets the value of the 'PupilSize' field.
   * @param value the value to set.
   */
  public void setPupilSize(java.lang.Double value) {
    this.PupilSize = value;
  }

  /**
   * Gets the value of the 'FixationDuration' field.
   * @return The value of the 'FixationDuration' field.
   */
  public java.lang.Double getFixationDuration() {
    return FixationDuration;
  }

  /**
   * Sets the value of the 'FixationDuration' field.
   * @param value the value to set.
   */
  public void setFixationDuration(java.lang.Double value) {
    this.FixationDuration = value;
  }

  /**
   * Gets the value of the 'AOI' field.
   * @return The value of the 'AOI' field.
   */
  public java.lang.CharSequence getAOI() {
    return AOI;
  }

  /**
   * Sets the value of the 'AOI' field.
   * @param value the value to set.
   */
  public void setAOI(java.lang.CharSequence value) {
    this.AOI = value;
  }

  /**
   * Creates a new TranslatedFixation RecordBuilder.
   * @return A new TranslatedFixation RecordBuilder
   */
  public static magicalpipelines.model.TranslatedFixation.Builder newBuilder() {
    return new magicalpipelines.model.TranslatedFixation.Builder();
  }

  /**
   * Creates a new TranslatedFixation RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new TranslatedFixation RecordBuilder
   */
  public static magicalpipelines.model.TranslatedFixation.Builder newBuilder(magicalpipelines.model.TranslatedFixation.Builder other) {
    return new magicalpipelines.model.TranslatedFixation.Builder(other);
  }

  /**
   * Creates a new TranslatedFixation RecordBuilder by copying an existing TranslatedFixation instance.
   * @param other The existing instance to copy.
   * @return A new TranslatedFixation RecordBuilder
   */
  public static magicalpipelines.model.TranslatedFixation.Builder newBuilder(magicalpipelines.model.TranslatedFixation other) {
    return new magicalpipelines.model.TranslatedFixation.Builder(other);
  }

  /**
   * RecordBuilder for TranslatedFixation instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<TranslatedFixation>
    implements org.apache.avro.data.RecordBuilder<TranslatedFixation> {

    private long Timestamp;
    private double Xpos;
    private double Ypos;
    private double PupilSize;
    private double FixationDuration;
    private java.lang.CharSequence AOI;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(magicalpipelines.model.TranslatedFixation.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.Timestamp)) {
        this.Timestamp = data().deepCopy(fields()[0].schema(), other.Timestamp);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.Xpos)) {
        this.Xpos = data().deepCopy(fields()[1].schema(), other.Xpos);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.Ypos)) {
        this.Ypos = data().deepCopy(fields()[2].schema(), other.Ypos);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.PupilSize)) {
        this.PupilSize = data().deepCopy(fields()[3].schema(), other.PupilSize);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.FixationDuration)) {
        this.FixationDuration = data().deepCopy(fields()[4].schema(), other.FixationDuration);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.AOI)) {
        this.AOI = data().deepCopy(fields()[5].schema(), other.AOI);
        fieldSetFlags()[5] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing TranslatedFixation instance
     * @param other The existing instance to copy.
     */
    private Builder(magicalpipelines.model.TranslatedFixation other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.Timestamp)) {
        this.Timestamp = data().deepCopy(fields()[0].schema(), other.Timestamp);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.Xpos)) {
        this.Xpos = data().deepCopy(fields()[1].schema(), other.Xpos);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.Ypos)) {
        this.Ypos = data().deepCopy(fields()[2].schema(), other.Ypos);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.PupilSize)) {
        this.PupilSize = data().deepCopy(fields()[3].schema(), other.PupilSize);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.FixationDuration)) {
        this.FixationDuration = data().deepCopy(fields()[4].schema(), other.FixationDuration);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.AOI)) {
        this.AOI = data().deepCopy(fields()[5].schema(), other.AOI);
        fieldSetFlags()[5] = true;
      }
    }

    /**
      * Gets the value of the 'Timestamp' field.
      * @return The value.
      */
    public java.lang.Long getTimestamp() {
      return Timestamp;
    }

    /**
      * Sets the value of the 'Timestamp' field.
      * @param value The value of 'Timestamp'.
      * @return This builder.
      */
    public magicalpipelines.model.TranslatedFixation.Builder setTimestamp(long value) {
      validate(fields()[0], value);
      this.Timestamp = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'Timestamp' field has been set.
      * @return True if the 'Timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'Timestamp' field.
      * @return This builder.
      */
    public magicalpipelines.model.TranslatedFixation.Builder clearTimestamp() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'Xpos' field.
      * @return The value.
      */
    public java.lang.Double getXpos() {
      return Xpos;
    }

    /**
      * Sets the value of the 'Xpos' field.
      * @param value The value of 'Xpos'.
      * @return This builder.
      */
    public magicalpipelines.model.TranslatedFixation.Builder setXpos(double value) {
      validate(fields()[1], value);
      this.Xpos = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'Xpos' field has been set.
      * @return True if the 'Xpos' field has been set, false otherwise.
      */
    public boolean hasXpos() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'Xpos' field.
      * @return This builder.
      */
    public magicalpipelines.model.TranslatedFixation.Builder clearXpos() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'Ypos' field.
      * @return The value.
      */
    public java.lang.Double getYpos() {
      return Ypos;
    }

    /**
      * Sets the value of the 'Ypos' field.
      * @param value The value of 'Ypos'.
      * @return This builder.
      */
    public magicalpipelines.model.TranslatedFixation.Builder setYpos(double value) {
      validate(fields()[2], value);
      this.Ypos = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'Ypos' field has been set.
      * @return True if the 'Ypos' field has been set, false otherwise.
      */
    public boolean hasYpos() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'Ypos' field.
      * @return This builder.
      */
    public magicalpipelines.model.TranslatedFixation.Builder clearYpos() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'PupilSize' field.
      * @return The value.
      */
    public java.lang.Double getPupilSize() {
      return PupilSize;
    }

    /**
      * Sets the value of the 'PupilSize' field.
      * @param value The value of 'PupilSize'.
      * @return This builder.
      */
    public magicalpipelines.model.TranslatedFixation.Builder setPupilSize(double value) {
      validate(fields()[3], value);
      this.PupilSize = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'PupilSize' field has been set.
      * @return True if the 'PupilSize' field has been set, false otherwise.
      */
    public boolean hasPupilSize() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'PupilSize' field.
      * @return This builder.
      */
    public magicalpipelines.model.TranslatedFixation.Builder clearPupilSize() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'FixationDuration' field.
      * @return The value.
      */
    public java.lang.Double getFixationDuration() {
      return FixationDuration;
    }

    /**
      * Sets the value of the 'FixationDuration' field.
      * @param value The value of 'FixationDuration'.
      * @return This builder.
      */
    public magicalpipelines.model.TranslatedFixation.Builder setFixationDuration(double value) {
      validate(fields()[4], value);
      this.FixationDuration = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'FixationDuration' field has been set.
      * @return True if the 'FixationDuration' field has been set, false otherwise.
      */
    public boolean hasFixationDuration() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'FixationDuration' field.
      * @return This builder.
      */
    public magicalpipelines.model.TranslatedFixation.Builder clearFixationDuration() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'AOI' field.
      * @return The value.
      */
    public java.lang.CharSequence getAOI() {
      return AOI;
    }

    /**
      * Sets the value of the 'AOI' field.
      * @param value The value of 'AOI'.
      * @return This builder.
      */
    public magicalpipelines.model.TranslatedFixation.Builder setAOI(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.AOI = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'AOI' field has been set.
      * @return True if the 'AOI' field has been set, false otherwise.
      */
    public boolean hasAOI() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'AOI' field.
      * @return This builder.
      */
    public magicalpipelines.model.TranslatedFixation.Builder clearAOI() {
      AOI = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public TranslatedFixation build() {
      try {
        TranslatedFixation record = new TranslatedFixation();
        record.Timestamp = fieldSetFlags()[0] ? this.Timestamp : (java.lang.Long) defaultValue(fields()[0]);
        record.Xpos = fieldSetFlags()[1] ? this.Xpos : (java.lang.Double) defaultValue(fields()[1]);
        record.Ypos = fieldSetFlags()[2] ? this.Ypos : (java.lang.Double) defaultValue(fields()[2]);
        record.PupilSize = fieldSetFlags()[3] ? this.PupilSize : (java.lang.Double) defaultValue(fields()[3]);
        record.FixationDuration = fieldSetFlags()[4] ? this.FixationDuration : (java.lang.Double) defaultValue(fields()[4]);
        record.AOI = fieldSetFlags()[5] ? this.AOI : (java.lang.CharSequence) defaultValue(fields()[5]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<TranslatedFixation>
    WRITER$ = (org.apache.avro.io.DatumWriter<TranslatedFixation>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<TranslatedFixation>
    READER$ = (org.apache.avro.io.DatumReader<TranslatedFixation>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
